Swift conversion
selfconference/selfconf-ios pull request #12
Opened 2019-05-29 01:33 UTC by FlaviusBortas

### What does this PR do? :soccer:

* Lowers the deployment target to iOS 11 (current version -1)
* Adds a bridging header file and exposes MBProgressHud to Swift.
* Converts Objective-C code to Swift.

### Tell me about any important implementation details. :construction:

### How can this PR be tested? :mag:

Regression testing should be done

2019-05-29 02:02 UTC, FlaviusBortas commented
@SlaunchaMan @jeffaburt 
I've updated some Obj-C code to swift, I'd appreciate it if I could get a review from one of you. Any and all feedback is welcomed 😁

2019-05-29 13:21 UTC, BritneyS requested changes
Just requested one change, but overall good job! 🌮

2019-05-29 13:21 UTC, BritneyS commented on SelfConference/Categories/UIColor+SCColor.swift
> +    static let scTeal  = UIColor(named: "SC_teal")!
Instead of forcibly unwrapping the colors, nil coalescing can be used to establish color defaults, like:

```
static let scTeal  = UIColor(named: "SC_teal") ?? UIColor(red:51, green:145, blue:148, alpha:1.00)
```

2019-05-29 13:21 UTC, BritneyS commented on SelfConference/Constants.swift
> +    private override init() {}
Good job locking up this temporary class as much as possible 🔒 🔑

2019-05-29 13:31 UTC, BritneyS reviewed
Regression tests passed, plus: Sponsors list is fixed 🎉 

![Simulator Screen Shot - iPhone X - 2019-05-29 at 09 28 23](https://user-images.githubusercontent.com/8409475/58561127-723b4100-81f4-11e9-806a-0238799dbc4d.png)

2019-05-29 15:47 UTC, FlaviusBortas commented
@BritneyS Thanks for the feedback Britney, I envisioned having the color asset catalog as the singe source of truth for getting and updating colors. Then if a crash were to happen there would be only one place to look at, the asset catalog. But it is safer to have a fallback color if it crashes so I’ll make those changes 😄. We just need to remember that if we make updates to a color we need to update it in the asset catalog and within the extension.

2019-05-30 13:07 UTC, BritneyS approved these changes
Looks good to me 👍

2019-05-30 13:08 UTC, merged